### ISSUE TITLE
Any update? Appolo-server is graphql-server-express now.

### ISSUE THREAD

**Issue by MichelDiz** [rohanray/graphql-digital-transformation#5]
I started to study GraphQL and now I'm studying your repo.

Best regards

**Comment by rohanray** [comment]
Hi @MichelDiz 

This project was created for an open source hackathon event. Unfortunately, we don't intend to maintain this project.

I am indeed glad that you did try this repo :) I would suggest following Graphql or Apollo community for further deep diving.

Thanks,
-R
